<a href="https://colab.research.google.com/github/Djuikem/Master_Thesis_AIMS/blob/main/Hybride_DL_to_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Install necessary packages for Colab
!pip install -q scikit-learn
!pip install -q matplotlib
!pip install -q torch torchvision torchaudio

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 107.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 82.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 48.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 14.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 36.2 MB/s eta 0:00:00


In [ ]:
!pip install gensim numpy==2 scipy==1.14.0

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 839.8 kB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 kB 2.5 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of gensim to determine which version is compatible with other requirements. This could take a while.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.3/19.3 MB 33.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.1/41.1 MB 13.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 81.5 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.3
    Uninstalling scipy-1.15.3:
      Successfully uninstalled scipy-1.15.3


In [ ]:
!pip install scipy==1.12.0

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 kB 2.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.4/38.4 MB 21.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 59.6 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.0
    Uninstalling numpy-2.0.0:
      Successfully uninstalled numpy-2.0.0
  Attempting uninstall: scipy
    Found existing installation: scipy 1.14.0
    Uninstalling scipy-1.14.0:
      Successfully uninstalled scipy-1.14.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tsfresh 0.21.0 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.12.0 which is incompatible.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from torch.nn.utils.rnn import pad_sequence

import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

import tensorflow as tf

from IPython import get_ipython
from IPython.display import display

from sklearn import metrics
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report,  roc_curve, auc
from sklearn import model_selection
from sklearn.model_selection import train_test_split
from sklearn.datasets import fetch_20newsgroups
from sklearn.dummy import DummyClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from gensim.models import Word2Vec # ⚒️

# Downloading the data

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Textual_data/Combined Data.csv')
df, _ = train_test_split(df, test_size=0.8, random_state=42, stratify=df['status'])
df.shape

(10608, 3)

# Preprocessing of the data

In [ ]:
# Download NLTK resources if needed
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
# Download the punkt_tab data package
nltk.download('punkt_tab')


# Load data
df = df.dropna(subset=['statement'])  # Drop rows with missing statements

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


In [ ]:
sentences = []
targets = []


for index in df.index:  # Iterate over the actual index values
  sentence = df.loc[index, 'statement']

  sentence = re.sub(r'[^\w\s]', '', sentence)
  temp = []
  words = word_tokenize(sentence)
  if len(words) > 3 and len(words) < 200:
    for j in word_tokenize(sentence):
        temp.append(j.lower())
    sentences.append(temp)
    targets.append(df.loc[index, 'status'])

In [ ]:
# Train Word2Vec model
model = Word2Vec(sentences = sentences, vector_size=100, window=5, min_count=1, workers=4)

In [ ]:
# Function to convert sentences to vectors
def sentence_to_vector(sentence):
    vectors = [model.wv[word] for word in sentence if word in model.wv]
    # Return a NumPy array, or an empty array if no words are found
    return np.array(vectors) if vectors else np.empty((0, model.vector_size))

# Find the maximum length of any sentence
max_length = max(len(sentence_to_vector(sentence)) for sentence in sentences)

# Transform your text data into vectors
X = [sentence_to_vector(text) for text in sentences]

In [ ]:
# Padding or truncating sequences to ensure uniform length
X_padded = []
for vec in X:
    if vec.size == 0:  # Check if the vector is empty
        padded_vec = np.zeros((max_length, 100))  # Create a zero-filled array
    else:
        padded_vec = np.pad(vec, ((0, max_length - vec.shape[0]), (0, 0)), 'constant') if vec.shape[0] < max_length else vec[:max_length]
    X_padded.append(padded_vec)
X_padded = np.array(X_padded)

In [ ]:
targets = pd.Series(targets)

# Personnal Mapping
perso_mapping = {'Normal': 0, 'Bipolar': 1, 'Depression':2, 'Anxiety':3, 'Stress':4, 'Suicidal':5, 'Personality disorder':6}
y = targets.map(perso_mapping)

# Splitting the data

In [ ]:
from sklearn.model_selection import StratifiedShuffleSplit

# Step 1: Split into Train (70%) and Temp (30%)
sss1 = StratifiedShuffleSplit(n_splits=1, test_size=0.3, random_state=42)
for train_idx, temp_idx in sss1.split(X_padded, y):
    X_train, X_temp = X_padded[train_idx], X_padded[temp_idx]
    y_train, y_temp = y[train_idx], y[temp_idx]

# Convert y_temp to a NumPy array to allow positional indexing
y_temp_np = y_temp.to_numpy()

# Step 2: Split Temp into Validation (10%) and Test (20%)
# That means: 1/3 of 30% goes to val = 10%, and 2/3 to test = 20%
# Use the NumPy array y_temp_np for splitting
sss2 = StratifiedShuffleSplit(n_splits=1, test_size=2/3, random_state=42)
for test_idx, val_idx in sss2.split(X_temp, y_temp_np): # Use y_temp_np here
    X_test, X_val = X_temp[test_idx], X_temp[val_idx]
    # Index the NumPy array y_temp_np directly
    y_test, y_val = y_temp_np[test_idx], y_temp_np[val_idx] # Use y_temp_np here

In [ ]:
if isinstance(y_train, pd.Series):
    y_train = y_train.to_numpy().reshape(-1, 1)
else:
    y_train = y_train.reshape(-1, 1) # Reshape if already a numpy array

y_test = y_test.reshape(-1, 1)

In [ ]:
y_train = y_train.astype('int32')
y_test = y_test.astype('int32')

In [ ]:
X_train = tf.convert_to_tensor(np.array(X_train), dtype=tf.float32)
y_train = tf.convert_to_tensor(y_train, dtype=tf.int32)

X_test = tf.convert_to_tensor(np.array(X_test), dtype=tf.float32)
y_test = tf.convert_to_tensor(y_test, dtype=tf.int32)

In [ ]:
X_train = torch.from_numpy(np.array(X_train)).float()
# Convert TensorFlow tensor back to NumPy array before creating PyTorch tensor
y_train = torch.tensor(y_train.numpy(), dtype=torch.long) # Use torch.long for classification targets

X_test = torch.from_numpy(np.array(X_test)).float()
# Convert TensorFlow tensor back to NumPy array before creating PyTorch tensor
y_test = torch.tensor(y_test.numpy(), dtype=torch.long) # Use torch.long for classification targets

# Models Training and Feature extraction

# LSTM

In [ ]:
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

# Vérifie que X_train est bien en (B, S, F)
print("X_train shape:", X_train.shape)

# Si X_train est en (B, F), on le transforme en (B, 1, F)
if X_train.dim() == 2:
    X_train = X_train.unsqueeze(1)  # Ajoute une dimension de séquence

# ------------------ Classes ------------------

class LSTMFeatureExtractor(nn.Module):
    def __init__(self, input_size: int, hidden_size: int, num_layers: int = 2,
                 bidirectional: bool = True, dropout: float = 0.2, use_pooling: bool = False):
        super().__init__()
        self.use_pooling = use_pooling
        self.bidirectional = bidirectional
        self.lstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            dropout=dropout if num_layers > 1 else 0.0,
            batch_first=True,
            bidirectional=bidirectional
        )
        self.output_size = hidden_size * (2 if bidirectional else 1)
        self.norm = nn.LayerNorm(self.output_size)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        assert x.dim() == 3, f"Expected input of shape (B, S, F), got {x.shape}"
        output, (h_n, _) = self.lstm(x)
        if self.bidirectional:
            features = torch.cat((h_n[-2], h_n[-1]), dim=1)
        else:
            features = h_n[-1]
        return self.norm(features)

class LSTMClassifier(nn.Module):
    def __init__(self, input_size: int, hidden_size: int, num_classes: int,
                 num_layers: int = 2, bidirectional: bool = True, dropout: float = 0.2):
        super().__init__()
        self.feature_extractor = LSTMFeatureExtractor(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            bidirectional=bidirectional,
            dropout=dropout
        )
        self.classifier = nn.Linear(self.feature_extractor.output_size, num_classes)

    def forward(self, x):
        features = self.feature_extractor(x)
        return self.classifier(features)

# ------------------ Entraînement ------------------

model = LSTMClassifier(input_size=100, hidden_size=64, num_classes=7)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

batch_size = 32
train_dataset = TensorDataset(X_train.float(), y_train.long())
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

for epoch in range(20):
    model.train()
    total_loss = 0
    for batch_x, batch_y in train_loader:
        optimizer.zero_grad()
        outputs = model(batch_x)
        batch_y = batch_y.squeeze()
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")


X_train shape: torch.Size([5819, 199, 100])
Epoch 1, Loss: 231.8526
Epoch 2, Loss: 196.7538
Epoch 3, Loss: 182.6827
Epoch 4, Loss: 174.7077
Epoch 5, Loss: 163.7318
Epoch 6, Loss: 154.0191
Epoch 7, Loss: 145.7646
Epoch 8, Loss: 139.6035
Epoch 9, Loss: 132.0665
Epoch 10, Loss: 126.6004
Epoch 11, Loss: 119.6767
Epoch 12, Loss: 114.1834
Epoch 13, Loss: 106.6189
Epoch 14, Loss: 100.4692
Epoch 15, Loss: 95.4932
Epoch 16, Loss: 89.3482
Epoch 17, Loss: 80.5004
Epoch 18, Loss: 75.6929
Epoch 19, Loss: 73.8552
Epoch 20, Loss: 65.5860


In [ ]:
feature_model_lstm = model.feature_extractor

# GRU

In [ ]:
import torch
import torch.nn as nn

class GRUFeatureExtractor(nn.Module):
    """
    Improved GRU-based feature extractor with optional bidirectionality, pooling, dropout, and normalization.
    """
    def __init__(self,
                 input_size: int,
                 hidden_size: int,
                 num_layers: int = 2,
                 bidirectional: bool = True,
                 dropout: float = 0.2,
                 use_pooling: bool = False):
        super().__init__()
        self.use_pooling = use_pooling
        self.bidirectional = bidirectional

        self.gru = nn.GRU(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            bidirectional=bidirectional,
            dropout=dropout if num_layers > 1 else 0.0
        )

        self.output_size = hidden_size * (2 if bidirectional else 1)
        self.norm = nn.LayerNorm(self.output_size)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        assert x.dim() == 3, f"Expected input of shape (B, S, F), got {x.shape}"

        output, h_n = self.gru(x)

        if self.use_pooling:
            # Moyenne temporelle (pooling sur toute la séquence)
            features = output.mean(dim=1)
        else:
            # Use the last hidden state(s) from the last layer
            if self.bidirectional:
                # Concatenate forward and backward hidden states from the last layer
                features = torch.cat((h_n[-2, :, :], h_n[-1, :, :]), dim=1)
            else:
                # Use the last hidden state of the last layer for unidirectional
                features = h_n[-1, :, :]

        return self.norm(features)


class GRUClassifier(nn.Module):
    def __init__(self, input_size: int, hidden_size: int, num_classes: int,
                 num_layers: int = 2, bidirectional: bool = True, dropout: float = 0.2):
        super().__init__()
        self.feature_extractor = GRUFeatureExtractor(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            bidirectional=bidirectional,
            dropout=dropout
        )
        self.classifier = nn.Linear(self.feature_extractor.output_size, num_classes)

    def forward(self, x):
        features = self.feature_extractor(x)
        return self.classifier(features)

# Modèle
model1 = GRUClassifier(input_size=100, hidden_size=64, num_classes=7)  # Ajuste input_size
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model1.parameters(), lr=1e-3)

# DataLoader
batch_size = 32
train_dataset = TensorDataset(X_train.float(), y_train.long().squeeze())
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

# Entraînement
for epoch in range(10):
    model1.train()
    total_loss = 0
    for batch_x, batch_y in train_loader:
        optimizer.zero_grad()
        outputs = model1(batch_x)
        batch_y = batch_y.squeeze()  # just in case
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

Epoch 1, Loss: 228.5250
Epoch 2, Loss: 177.7923
Epoch 3, Loss: 162.3538
Epoch 4, Loss: 152.0652
Epoch 5, Loss: 143.5209
Epoch 6, Loss: 136.5296
Epoch 7, Loss: 129.0651
Epoch 8, Loss: 124.0574
Epoch 9, Loss: 116.1854
Epoch 10, Loss: 110.2839


In [ ]:
feature_model_GRU = model1.feature_extractor

# Transformers

In [ ]:
class PositionalEncoding(nn.Module):
    def __init__(self, d_model: int, max_len: int = 500):
        super().__init__()
        position = torch.arange(max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2, dtype=torch.float) * (-np.log(10000.0) / d_model))
        pe = torch.zeros(max_len, d_model)
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        pe = pe.unsqueeze(0)  # shape: (1, max_len, d_model)
        self.register_buffer("pe", pe)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # x: (B, S, D)
        return x + self.pe[:, :x.size(1)].to(x.dtype)


class TransformerFeatureExtractor(nn.Module):
    """
    Transformer-based feature extractor with flexible pooling and improved embedding.
    """
    def __init__(self,
                 input_size: int,
                 d_model: int = 64,
                 nhead: int = 4,
                 num_layers: int = 2,
                 max_len: int = 500,
                 dropout_rate: float = 0.1,
                 pooling: str = 'mean'  # options: 'mean', 'max', 'cls'
                 ):
        super().__init__()
        self.pooling = pooling

        self.embedding = nn.Sequential(
            nn.Linear(input_size, d_model),
            nn.LayerNorm(d_model),
            nn.Dropout(dropout_rate)
        )

        self.pos_encoder = PositionalEncoding(d_model, max_len=max_len)

        encoder_layer = nn.TransformerEncoderLayer(d_model=d_model,
                                                   nhead=nhead,
                                                   dropout=dropout_rate,
                                                   batch_first=False)
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)

        self.output_size = d_model
        self.dropout = nn.Dropout(dropout_rate)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        assert x.dim() == 3, f"Expected input of shape (B, S, F), got {x.shape}"

        x = self.embedding(x)           # (B, S, D)
        x = self.pos_encoder(x)         # (B, S, D)
        x = x.permute(1, 0, 2)          # (S, B, D)
        x = self.transformer(x)         # (S, B, D)
        x = x.permute(1, 0, 2)          # (B, S, D)

        if self.pooling == 'mean':
            features = x.mean(dim=1)
        elif self.pooling == 'max':
            features, _ = x.max(dim=1)
        elif self.pooling == 'cls':
            features = x[:, 0, :]  # suppose que le token [CLS] est le premier
        else:
            raise ValueError(f"Unknown pooling method: {self.pooling}")

        return self.dropout(features)

class TransformerClassifier(nn.Module):
    def __init__(self, input_size: int, num_classes: int,
                 d_model: int = 64, nhead: int = 4, num_layers: int = 2,
                 dropout_rate: float = 0.1, pooling: str = 'mean'):
        super().__init__()
        self.feature_extractor = TransformerFeatureExtractor(
            input_size=input_size,
            d_model=d_model,
            nhead=nhead,
            num_layers=num_layers,
            dropout_rate=dropout_rate,
            pooling=pooling
        )
        self.classifier = nn.Linear(self.feature_extractor.output_size, num_classes)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        features = self.feature_extractor(x)
        return self.classifier(features)

# Création du modèle
model2 = TransformerClassifier(input_size=100, num_classes=7)

# Fonction de perte et optimiseur
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model2.parameters(), lr=1e-3)

# DataLoader
batch_size = 32
train_dataset = TensorDataset(X_train.float(), y_train.long())
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

# Entraînement
for epoch in range(20):
    model2.train()
    total_loss = 0
    for batch_x, batch_y in train_loader:
        optimizer.zero_grad()
        outputs = model2(batch_x)
        batch_y = batch_y.squeeze()  # S'assurer que les labels sont 1D
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(


Epoch 1, Loss: 231.9998
Epoch 2, Loss: 188.9344
Epoch 3, Loss: 176.2791
Epoch 4, Loss: 166.5117
Epoch 5, Loss: 158.7657
Epoch 6, Loss: 151.0386
Epoch 7, Loss: 146.1492
Epoch 8, Loss: 146.6983
Epoch 9, Loss: 141.7597
Epoch 10, Loss: 137.2701
Epoch 11, Loss: 135.8291
Epoch 12, Loss: 129.2512
Epoch 13, Loss: 125.2320
Epoch 14, Loss: 125.5763
Epoch 15, Loss: 121.3606
Epoch 16, Loss: 120.4887
Epoch 17, Loss: 115.5848
Epoch 18, Loss: 115.0113
Epoch 19, Loss: 111.2712
Epoch 20, Loss: 109.3387


In [ ]:
feature_model_Transformer = model2.feature_extractor

# Classification with SVM model

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import GridSearchCV


def extract_features(model, X_tensor, batch_size=32):
    """
    Extrait les caractéristiques d'un modèle PyTorch.
    Entrée : tenseur de forme (N, S, F)
    Sortie : numpy array de caractéristiques extraites
    """
    model.eval()
    dataset = DataLoader(X_tensor, batch_size=batch_size)

    features = []
    with torch.no_grad():
        for batch in dataset:
            outputs = model(batch)
            features.append(outputs)

    return torch.cat(features, dim=0).numpy()

def train_feature_svm(feature_model, kernel='rbf', C=10, gamma='scale'):
    """
    Entraîne un SVM basé sur les features extraites d'un modèle deep learning.
    Affiche un rapport de classification et retourne les métriques principales.
    """
    # Extraire les caractéristiques à partir du modèle
    features_train = extract_features(feature_model, X_train)
    features_test = extract_features(feature_model, X_test)

    #Recherche d'hyperparametres
    param_grid = {'C': [0.1, 1, 10], 'gamma': ['scale', 'auto'], 'kernel': ['rbf', 'linear']}
    grid = GridSearchCV(SVC(probability=True), param_grid, cv=3, scoring='f1_weighted')
    grid.fit(features_train, y_train)
    print(grid.best_params_)
    C = grid.best_params_['C']
    gamma = grid.best_params_['gamma']

    # Entraîner le SVM
    svm = SVC(kernel=kernel, C=C, gamma=gamma, probability=True)
    svm.fit(features_train, y_train)
    y_pred = svm.predict(features_test)

    # Affichage du rapport
    print("\n✅ Classification Report:\n", classification_report(y_test, y_pred))
    print("\n📊 Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

    # Retour des scores
    return {
        'Accuracy': accuracy_score(y_test, y_pred),
        'Precision': precision_score(y_test, y_pred, average='weighted'),
        'Recall': recall_score(y_test, y_pred, average='weighted'),
        'F1': f1_score(y_test, y_pred, average='weighted')
    }


In [ ]:
# lstm_model = LSTMFeatureExtractor(input_size=100, hidden_size=256)
lstm_results = train_feature_svm(feature_model_lstm)
print("LSTM → SVM Results:", lstm_results)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for exam

{'C': 0.1, 'gamma': 'scale', 'kernel': 'linear'}


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)



✅ Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.90      0.87       291
           1       0.43      0.39      0.41        38
           2       0.63      0.63      0.63       221
           3       0.46      0.42      0.44        57
           4       0.33      0.28      0.30        46
           5       0.57      0.59      0.58       163
           6       0.50      0.07      0.12        15

    accuracy                           0.66       831
   macro avg       0.54      0.47      0.48       831
weighted avg       0.65      0.66      0.65       831


📊 Confusion Matrix:
 [[263   1   6   6   6   9   0]
 [  1  15   7  10   3   1   1]
 [ 14   3 139   3   2  60   0]
 [  8  10   4  24  11   0   0]
 [ 11   2  12   7  13   1   0]
 [ 13   0  52   1   1  96   0]
 [  2   4   1   1   4   2   1]]
LSTM → SVM Results: {'Accuracy': 0.6630565583634176, 'Precision': 0.6521458477651202, 'Recall': 0.6630565583634176, 'F1': 0.654025144012

In [ ]:
# gru_model = GRUFeatureExtractor(input_size=100, hidden_size=256)
gru_results = train_feature_svm(feature_model_GRU)
print("GRU → SVM Results:", gru_results)


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for exam

{'C': 0.1, 'gamma': 'scale', 'kernel': 'linear'}


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)



✅ Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.91      0.88       291
           1       0.38      0.34      0.36        38
           2       0.71      0.59      0.65       221
           3       0.48      0.49      0.49        57
           4       0.44      0.41      0.43        46
           5       0.58      0.71      0.64       163
           6       0.00      0.00      0.00        15

    accuracy                           0.69       831
   macro avg       0.49      0.49      0.49       831
weighted avg       0.67      0.69      0.68       831


📊 Confusion Matrix:
 [[266   1   3   4   5  12   0]
 [  1  13   7  10   6   1   0]
 [ 13   1 131   6   2  68   0]
 [  8  11   1  28   8   1   0]
 [  8   5   8   6  19   0   0]
 [ 14   0  33   1   0 115   0]
 [  3   3   2   3   3   1   0]]
GRU → SVM Results: {'Accuracy': 0.6883273164861613, 'Precision': 0.6748969410107953, 'Recall': 0.6883273164861613, 'F1': 0.6785759695992

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/m

In [ ]:
# transformer_model = TransformerFeatureExtractor(input_size=100, d_model=256, nhead=8, num_layers=3) # Changed input_size from 20 to 100
transformer_results = train_feature_svm(feature_model_Transformer)
print("Transformer → SVM Results:", transformer_results)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for exam

{'C': 1, 'gamma': 'scale', 'kernel': 'linear'}


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)



✅ Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.91      0.90       291
           1       0.78      0.74      0.76        38
           2       0.74      0.66      0.70       221
           3       0.75      0.81      0.78        57
           4       0.65      0.57      0.60        46
           5       0.61      0.72      0.66       163
           6       0.56      0.33      0.42        15

    accuracy                           0.76       831
   macro avg       0.71      0.68      0.69       831
weighted avg       0.76      0.76      0.76       831


📊 Confusion Matrix:
 [[265   0   7   2   6  11   0]
 [  1  28   4   3   2   0   0]
 [  8   5 145   1   1  60   1]
 [  2   2   0  46   4   1   2]
 [  5   1   5   7  26   1   1]
 [ 13   0  33   0   0 117   0]
 [  4   0   2   2   1   1   5]]
Transformer → SVM Results: {'Accuracy': 0.7605294825511432, 'Precision': 0.7616013582791235, 'Recall': 0.7605294825511432, 'F1': 0.75878

# Hybride-parallel

In [ ]:
# reshape
X_padded = X_padded.reshape(X_padded.shape[0], -1)
X_padded.shape

(8313, 19900)

In [ ]:

# Step 1: Split into Train (70%) and Temp (30%)
sss1 = StratifiedShuffleSplit(n_splits=1, test_size=0.3, random_state=42)
for train_idx, temp_idx in sss1.split(X_padded, y):
    X_train2, X_temp = X_padded[train_idx], X_padded[temp_idx]
    y_train2, y_temp = y[train_idx], y[temp_idx]

# Convert y_temp to a NumPy array to allow positional indexing
y_temp_np = y_temp.to_numpy()

# Step 2: Split Temp into Validation (10%) and Test (20%)
# That means: 1/3 of 30% goes to val = 10%, and 2/3 to test = 20%
# Use the NumPy array y_temp_np for splitting
sss2 = StratifiedShuffleSplit(n_splits=1, test_size=2/3, random_state=42)
for test_idx, val_idx in sss2.split(X_temp, y_temp_np): # Use y_temp_np here
    X_test2, X_val2 = X_temp[test_idx], X_temp[val_idx]
    # Index the NumPy array y_temp_np directly
    y_test2, y_val2 = y_temp_np[test_idx], y_temp_np[val_idx] # Use y_temp_np here



In [ ]:

print("X_train shape:", X_train2.shape)
print("X_test shape:", X_test2.shape)
print("Max token value:", np.max(X_train2))


X_train shape: (5819, 19900)
X_test shape: (831, 19900)
Max token value: 3.233741


In [ ]:

# Ensemble: Average probabilities from SVM and LSTM classifier
from sklearn.linear_model import LogisticRegression

'''
#Recherche d'hyperparametres
param_grid = {'C': [0.1, 1, 10], 'gamma': ['scale', 'auto'], 'kernel': ['rbf', 'linear']}
grid = GridSearchCV(SVC(probability=True), param_grid, cv=3, scoring='f1_weighted')
grid.fit(X_train2, y_train2)
print(grid.best_params_)
C = grid.best_params_['C']
gamma = grid.best_params_['gamma']
'''

# Train SVM
svm = SVC(kernel='rbf', C=10, gamma='scale', probability=True)
svm.fit(X_train2, y_train2)
y_pred = svm.predict(X_test2)
# prob_svm = svm.predict_proba(X_test2)[:, 1]



In [ ]:
prob_svm = svm.predict_proba(X_test2)


In [ ]:

# 📌 TensorFlow/Keras imports
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Dense, LSTM, GRU, Conv1D, Flatten, Dropout, MultiHeadAttention, LayerNormalization, Input, Reshape, Add, SimpleRNN
from tensorflow.keras.optimizers import Adam
import cvxopt  # For optimization in SVM-based models
# Import GlobalAveragePooling1D from tensorflow.keras.layers
from tensorflow.keras.layers import  GlobalAveragePooling1D, Layer
'''
class PositionalEncodingLayer(Layer):
    def __init__(self):
        super().__init__()

    def call(self, x):
        positions = tf.range(start=0, limit=tf.shape(x)[1], delta=1)
        pos_encoding = tf.cast(positions[:, tf.newaxis], dtype=tf.float32)
        return x + pos_encoding
'''

def transformer_block(x, num_heads, key_dim, ff_dim=128, dropout_rate=0.1):
  attention_output = MultiHeadAttention(num_heads=num_heads, key_dim=key_dim)(x, x)
  attention_output = Dropout(dropout_rate)(attention_output)
  attention_output = LayerNormalization(epsilon=1e-6)(attention_output + x)

  ff = Dense(ff_dim, activation='relu')(attention_output)
  ff = Dropout(dropout_rate)(ff)
  ff = Dense(key_dim)(ff)

  return LayerNormalization(epsilon=1e-6)(ff + attention_output)

def build_transformer(input_shape):
    inputs = Input(shape=input_shape)
    key_dim_val = 64  # ↓ Réduction de la dimension d’attention
    x = Dense(key_dim_val)(inputs) if input_shape[-1] != key_dim_val else inputs

    # x = PositionalEncodingLayer()(x)  # ← Ajout de l'encodage positionnel

    x = transformer_block(x, num_heads=2, key_dim=key_dim_val)  # ↓ Moins de têtes
    x = transformer_block(x, num_heads=2, key_dim=key_dim_val)

    x = GlobalAveragePooling1D()(x)
    x = Dense(32, activation='relu')(x)  # ↓ Taille de couche intermédiaire
    x = Dropout(0.2)(x)
    # x = Dense(64, activation='relu')(x)
    output = Dense(7, activation='softmax')(x)

    model = Model(inputs=inputs, outputs=output)
    model.compile(optimizer=Adam(learning_rate=0.001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model



transformer_model = build_transformer(X_train.shape[1:])
transformer_model.fit(X_train, y_train, epochs=20, batch_size=64, verbose=0)
prob_transformer = transformer_model.predict(X_test, verbose=0)

# --- Debugging: Check shapes before combining ---
print("Shape of prob_svm:", prob_svm.shape)
print("Shape of prob_transformer:", prob_transformer.shape)
# --- End Debugging ---

# Ensemble
# prob_ensemble = (prob_svm[:10] + prob_dl) / 2
# pred_ensemble = np.argmax(prob_ensemble, axis=1)
# print("Ensemble accuracy:", accuracy_score(y_test, pred_ensemble))

if prob_svm.shape == prob_transformer.shape:
    prob_ensemble = (prob_svm + prob_transformer) / 2
    pred_ensemble = np.argmax(prob_ensemble, axis=1)
    print("Ensemble accuracy:", accuracy_score(y_test2, pred_ensemble)) # Use y_test2 for the flattened data split

    precision = precision_score(y_test2, pred_ensemble, average='weighted')
    recall = recall_score(y_test2, pred_ensemble, average='weighted')
    f1 = f1_score(y_test2, pred_ensemble, average='weighted')

    print(f"Precision: {precision:.4f}")
    print(f"Recall:    {recall:.4f}")
    print(f"F1-score:  {f1:.4f}")

    # Classification report
    print("\n📊 Ensemble Classification Report:")
    print(classification_report(y_test2, pred_ensemble, digits=4))  # digits=4 for more precision
else:
    print("Error: Probability shapes mismatch for ensemble.")
    print("prob_svm shape:", prob_svm.shape)
    print("prob_transformer shape:", prob_transformer.shape)


Shape of prob_svm: (831, 7)
Shape of prob_transformer: (831, 7)
Ensemble accuracy: 0.7388688327316486
Precision: 0.7403
Recall:    0.7389
F1-score:  0.7305

📊 Ensemble Classification Report:
              precision    recall  f1-score   support

           0     0.8770    0.9313    0.9033       291
           1     0.5556    0.7895    0.6522        38
           2     0.6833    0.6833    0.6833       221
           3     0.6216    0.8070    0.7023        57
           4     0.6087    0.3043    0.4058        46
           5     0.6712    0.6012    0.6343       163
           6     1.0000    0.2667    0.4211        15

    accuracy                         0.7389       831
   macro avg     0.7168    0.6262    0.6289       831
weighted avg     0.7403    0.7389    0.7305       831



In [ ]:
'''
def build_lstm(input_shape):
    model = Sequential([
        Input(shape=input_shape),
        LSTM(64, return_sequences=True),
        LSTM(48, return_sequences=True),
        LSTM(32, return_sequences=True),  # 32 neurons and produces an output at each timestep
        LSTM(16),  # 16 LSTM units and produces the last output
        Dropout(0.3),
        Dense(64, activation='relu'),
        Dense(7, activation='softmax')  # Output layer
    ])
    model.compile(optimizer=Adam(), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model
'''
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, Dense, Dropout, Bidirectional, LayerNormalization

def build_lstm(input_shape):
    inputs = Input(shape=input_shape)

    x = Bidirectional(LSTM(64, return_sequences=True, dropout=0.2, recurrent_dropout=0.1))(inputs)
    x = Bidirectional(LSTM(48, return_sequences=True, dropout=0.2))(x)
    x = Bidirectional(LSTM(32, return_sequences=True, dropout=0.2))(x)
    x = Bidirectional(LSTM(16, dropout=0.2))(x)

    x = LayerNormalization()(x)
    x = Dropout(0.3)(x)

    x = Dense(64, activation='relu')(x)
    outputs = Dense(7, activation='softmax')(x)

    model = Model(inputs=inputs, outputs=outputs)
    model.compile(optimizer=Adam(learning_rate=1e-3),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

lstm_model = build_lstm(X_train.shape[1:])
lstm_model.fit(X_train, y_train, epochs=50, batch_size=64, verbose=0)
prob_lstm = lstm_model.predict(X_test, verbose=0)

# --- Debugging: Check shapes before combining ---
print("Shape of prob_svm:", prob_svm.shape)
print("Shape of prob_lstm:", prob_lstm.shape)
# --- End Debugging ---

# Ensemble
# prob_ensemble = (prob_svm[:10] + prob_dl) / 2
# pred_ensemble = np.argmax(prob_ensemble, axis=1)
# print("Ensemble accuracy:", accuracy_score(y_test, pred_ensemble))

if prob_svm.shape == prob_lstm.shape:
    prob_ensemble = (prob_svm + prob_lstm) / 2
    pred_ensemble = np.argmax(prob_ensemble, axis=1)
    print("Ensemble accuracy:", accuracy_score(y_test2, pred_ensemble)) # Use y_test2 for the flattened data split

    precision = precision_score(y_test2, pred_ensemble, average='weighted')
    recall = recall_score(y_test2, pred_ensemble, average='weighted')
    f1 = f1_score(y_test2, pred_ensemble, average='weighted')

    print(f"Precision: {precision:.4f}")
    print(f"Recall:    {recall:.4f}")
    print(f"F1-score:  {f1:.4f}")

    # Classification report
    print("\n📊 Ensemble Classification Report:")
    print(classification_report(y_test2, pred_ensemble, digits=4))  # digits=4 for more precision
else:
    print("Error: Probability shapes mismatch for ensemble.")
    print("prob_svm shape:", prob_svm.shape)
    print("prob_lstm shape:", prob_lstm.shape)


Shape of prob_svm: (831, 7)
Shape of prob_lstm: (831, 7)
Ensemble accuracy: 0.6594464500601684
Precision: 0.6348
Recall:    0.6594
F1-score:  0.6398

📊 Ensemble Classification Report:
              precision    recall  f1-score   support

           0     0.8449    0.9175    0.8797       291
           1     0.5000    0.1316    0.2083        38
           2     0.5854    0.6516    0.6167       221
           3     0.4203    0.5088    0.4603        57
           4     0.3462    0.1957    0.2500        46
           5     0.5732    0.5767    0.5749       163
           6     0.0000    0.0000    0.0000        15

    accuracy                         0.6594       831
   macro avg     0.4671    0.4260    0.4271       831
weighted avg     0.6348    0.6594    0.6398       831



/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/m

In [ ]:
prob_svm

array([[0.03860518, 0.17422501, 0.3045557 , ..., 0.14736951, 0.1182403 ,
        0.04671141],
       [0.04182473, 0.01988922, 0.58449738, ..., 0.02854623, 0.27169553,
        0.01674202],
       [0.00442356, 0.00478961, 0.60052767, ..., 0.00879629, 0.35530361,
        0.00943918],
       ...,
       [0.14415066, 0.35562892, 0.13586686, ..., 0.18272559, 0.0539766 ,
        0.02449984],
       [0.01306834, 0.00629829, 0.44180502, ..., 0.01037911, 0.50788201,
        0.01182551],
       [0.13167475, 0.13149756, 0.38335882, ..., 0.09501435, 0.15047808,
        0.0156604 ]])

In [ ]:
# Function to build the GRU model
'''
def build_gru(input_shape):
    model = Sequential([
        Input(shape=input_shape),
        GRU(64, return_sequences=True),
        GRU(48, return_sequences=True),
        GRU(32, return_sequences=True),  # 32 neurons and produces an output at each timestep
        GRU(16),  # 16 GRU units and produces the last output
        Dropout(0.3),
        Dense(64, activation='relu'),
        Dense(7, activation='softmax')  # Output layer
    ])
    model.compile(optimizer=Adam(), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model
'''
def build_gru(input_shape):
    inputs = Input(shape=input_shape)

    x = Bidirectional(GRU(64, return_sequences=True, dropout=0.2, recurrent_dropout=0.1))(inputs)
    x = Bidirectional(GRU(48, return_sequences=True, dropout=0.2))(x)
    x = Bidirectional(GRU(32, return_sequences=True, dropout=0.2))(x)
    x = Bidirectional(GRU(16, dropout=0.2))(x)

    x = LayerNormalization()(x)
    x = Dropout(0.3)(x)

    x = Dense(64, activation='relu')(x)
    x = Dense(32, activation='relu')(x)  # couche ajoutée
    outputs = Dense(7, activation='softmax')(x)

    model = Model(inputs=inputs, outputs=outputs)
    model.compile(optimizer=Adam(learning_rate=1e-3),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

gru_model = build_gru(X_train.shape[1:])
gru_model.fit(X_train, y_train, epochs=50, batch_size=64, verbose=0)
prob_gru = gru_model.predict(X_test, verbose=0)

# --- Debugging: Check shapes before combining ---
print("Shape of prob_svm:", prob_svm.shape)
print("Shape of prob_gru:", prob_gru.shape)
# --- End Debugging ---

# Ensemble
# prob_ensemble = (prob_svm[:10] + prob_dl) / 2
# pred_ensemble = np.argmax(prob_ensemble, axis=1)
# print("Ensemble accuracy:", accuracy_score(y_test, pred_ensemble))

if prob_svm.shape == prob_gru.shape:
    prob_ensemble = (prob_svm + prob_gru) / 2
    pred_ensemble = np.argmax(prob_ensemble, axis=1)
    print("Ensemble accuracy:", accuracy_score(y_test2, pred_ensemble)) # Use y_test2 for the flattened data split

    precision = precision_score(y_test2, pred_ensemble, average='weighted')
    recall = recall_score(y_test2, pred_ensemble, average='weighted')
    f1 = f1_score(y_test2, pred_ensemble, average='weighted')

    print(f"Precision: {precision:.4f}")
    print(f"Recall:    {recall:.4f}")
    print(f"F1-score:  {f1:.4f}")

    # Classification report
    print("\n📊 Ensemble Classification Report:")
    print(classification_report(y_test2, pred_ensemble, digits=4))  # digits=4 for more precision
else:
    print("Error: Probability shapes mismatch for ensemble.")
    print("prob_svm shape:", prob_svm.shape)
    print("prob_gru shape:", prob_gru.shape)


Shape of prob_svm: (831, 7)
Shape of prob_gru: (831, 7)
Ensemble accuracy: 0.6859205776173285
Precision: 0.6704
Recall:    0.6859
F1-score:  0.6765

📊 Ensemble Classification Report:
              precision    recall  f1-score   support

           0     0.8617    0.9210    0.8904       291
           1     0.3542    0.4474    0.3953        38
           2     0.6371    0.6833    0.6594       221
           3     0.6222    0.4912    0.5490        57
           4     0.4286    0.3913    0.4091        46
           5     0.5946    0.5399    0.5659       163
           6     0.0000    0.0000    0.0000        15

    accuracy                         0.6859       831
   macro avg     0.4998    0.4963    0.4956       831
weighted avg     0.6704    0.6859    0.6765       831



/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/m